apiVersion: v1
kind: BuildConfig
metadata:
  name: gocd-agent
  labels:
    build: gocd-agent
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/suttiruk046/infrastructure.git'
    contextDir: gocd/gocd-agent
    sourceSecret:
      name: github-secret
  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
      forcePull: false
      env:
        - name: GO_SERVER_URL
          value: 'https://gocd-server:8154/go'
  output:
    to:
      kind: ImageStreamTag
      name: 'gocd-agent:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
