apiVersion: v1
kind: DeploymentConfig
metadata:
  name: gocd-agent
  labels:
    app: gocd-agent
    role: infrastructure-ci
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
          - gocd-agent
        from:
          kind: ImageStreamTag
          name: 'gocd-agent:latest'
  replicas: 1
  revisionHistoryLimit: 1
  test: false
  selector:
    app: gocd-agent
    deploymentconfig: gocd-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gocd-agent
        deploymentconfig: gocd-agent
    spec:
      containers:
        - name: gocd-agent
          image: >-
            openshift/gocd-agent:latest
          env:
            - name: GO_SERVER_URL
              value: 'https://gocd-server:8154/go'
            - name: GOCD_AGENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-gocd
                  key: GOCD_AGENT_SECRET
            - name: GIT_COMMITTER_NAME
              value: gocd
            - name: GIT_COMMITTER_EMAIL
              value: gocd@localhost
            - name: GOCD_GITHUB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-gocd
                  key: GOCD_GITHUB_USERNAME
            - name: GOCD_GITHUB_ACCESS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-gocd
                  key: GOCD_GITHUB_ACCESS_TOKEN
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      serviceAccount: infrastructure-ci
      serviceAccountName: infrastructure-ci
