apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  labels:
    app: gocd-agent
  name: gocd-agent
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    kind: DeploymentConfig
    name: gocd-agent
  targetCPUUtilizationPercentage: 80
