apiVersion: v1
kind: Route
metadata:
  name: gocd-server
  labels:
    app: gocd-server
    router: internet-router
spec:
  host: gocd-server-dev.paas.com
  to:
    kind: Service
    name: gocd-server
    weight: 100
  port:
    targetPort: 8153-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
